### ISSUE TITLE
Resizer sidecar doesn't consistently increase the time interval during exponential backoff on errors

### ISSUE THREAD

**Issue by shalini-b** [kubernetes-csi/external-resizer#105]
csi-resizer v0.5 retries ControllerExpandVolume after random intervals of time instead of an increasing interval of time during exponential backoff on an error. 
Refer to the event logs I got when I tried to perform online expansion when the CSI driver supports offline expansion only - https://gist.github.com/shalini-b/e4c8256cd46eb096e0efc3ae322ba644. The time logged for each event is not consistently increasing. 

Steps to reproduce - 
1. Use a CSI driver which uses csi-resizer v0.5.0
2. Perform any operation which raises an error in ControllerExpandVolume call. For example, try executing an online volume expansion in a driver which only supports offline expansion. This will ensure csi-resizer keeps retrying ControllerExpandVolume till it succeeds.
3. Check the events logged in csi-resizer while it is retrying with exponential backoff.

**Comment by msau42** [comment]
/reopen
/remove-lifecycle rotten

@gnufied is this still an issue?
