### ISSUE TITLE
Use connection code from csi-utils library

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-resizer#11]
xref https://github.com/kubernetes-csi/external-resizer/pull/7

**Comment by mlmhl** [comment]
I will fix this after csi-utils lib updated.
/assign

**Comment by gnufied** [comment]
Fixed by https://github.com/kubernetes-csi/external-resizer/pull/15 

@mlmhl ^ PR addresses this. Let me know if I was wrong in closing this issue.

**Comment by mlmhl** [comment]
The PR lgtm except a little nit: My initial idea was to put all the code that interacts with the CSI driver in `pkg/client`, and the resizer only uses the `Client` interface to interact with the driver. But now the CSI related code is scattered across `pkg/client` and `pkg/resizer`, it's somewhat difficult to maintain and hard to add unit tests.

However this is not a blocker, so I will clean the code and add some unit tests when I have time.
