### ISSUE TITLE
resize failed and can't recover due to pvc rejection "Forbidden: field can not be less than previous value "

### ISSUE THREAD

**Issue by hoyho** [kubernetes-csi/external-resizer#132]
How to reproduce:
1. create a pvc with size 1Gi
2. resize to 10Pi, kubectl edit pvc xxx and update spec.resources.requests.storage to 10Pi
3.  assume the new request size 10Pi is too large， csi-driver and backend storage refuse to update and response an error to call of ControllerExpandVolume
![image](https://user-images.githubusercontent.com/8370967/102306089-6234af00-3f9c-11eb-9309-0f1932e92ee2.png)

5.  pvc status change into Resizing
![image](https://user-images.githubusercontent.com/8370967/102306656-b2604100-3f9d-11eb-9da9-7bd4be999b80.png)

6. when realize 10Pi is to large for a storage backend, try reedit(kubectl edit pvc xxx)  and set to a lower value, for example,1T
7. pvc reject to save: spec.resources.requests.storage: Forbidden: field can not be less than previous value
![image](https://user-images.githubusercontent.com/8370967/102306744-e20f4900-3f9d-11eb-815e-bbd75f19a708.png)

That mean we can never update the size again, because csi driver(storage backend) only accept a smaller size
but pvc don't allow resizing to a capacity less than previous value.
Since external-resizer have received a failed rpc response , can it do something to recover the pvc
for example reset the size?

**Comment by ripulpatel** [comment]
cc: @gnufied 
I think there should be a way to recover PVC when any kind of unintended failures or bugs due to storage sub-system, else PVC will forever be in the state pv resizing.

**Comment by stoneshi-yunify** [comment]
Any plan to fix this issue?

**Comment by gnufied** [comment]
yes - https://github.com/kubernetes/enhancements/issues/1790

**Comment by andreclaro** [comment]
Is there any workaround to manually fix this issue?
