### ISSUE TITLE
Use new csi-translation-lib version

### ISSUE THREAD

**Issue by TeweiLuo** [kubernetes-csi/external-resizer#147]
Need to use >=v0.21.0 in order to handle v1 topology key.

**Comment by msau42** [comment]
@Jiawei0227 can you help with this?

**Comment by Jiawei0227** [comment]
https://github.com/kubernetes-csi/external-resizer/pull/145

This should fix the issue.
And actually csi-translation-lib is already in 0.21.0, it is just using an alpha release tag but should have the fix we need. Anyways, let's wait for the PR above get merged.

**Comment by ialidzhikov** [comment]
#145 is now merged and released. @TeweiLuo , can we now close this issue?
