### ISSUE TITLE
Out of memory when running a lot of pods

### ISSUE THREAD

**Issue by stijndehaes** [kubernetes-csi/external-resizer#211]
In environments where we are running a lot of pods we see the external resizer going out of memory. 
In these environments we typically only run 10's of pvc's, but 1000's of pods.
I believe the [pod informer](https://github.com/kubernetes-csi/external-resizer/blob/a76b4d2afe86d8d273341592e8ad4f6636309ae5/pkg/controller/controller.go#L121) might be the culprit.
Doesn't starting an informer launch a cache? This means all pods are currently cached on the resizer, which leads to excessive memory use. The code isn't actually using the cache, I think the code is only interested in the `Add`, `Update`, `Delete` part and not in the cache.

If this is correct I am willing to create a PR to fix this

**Comment by gnufied** [comment]
The whole `handleInUse` thing is behind a flag and only applicable for use cases where a driver needs external-resizer to enforce offline only expansion strongly. If it is enabled in EKS with external-resizer, then that seems like a problem. cc @wongma7

**Comment by stijndehaes** [comment]
@gnufied you are right, resizing can be done online on AWS i think. Good catch

**Comment by stijndehaes** [comment]
I will close this ticket as this was fixed in the EBS CSI driver, by setting the argument correctly
