### ISSUE TITLE
Use protobuf(instead of json) in apiserver request

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-resizer#213]
https://github.com/kubernetes-csi/external-resizer/blob/a76b4d2afe86d8d273341592e8ad4f6636309ae5/cmd/csi-resizer/main.go#L121

external-resizer has list method in localcache resync(default every 10min). Is it possible to use the protobuf protocol to reduce the pressure on the apiserver?

**Comment by humblec** [comment]
Cc @gnufied
