### ISSUE TITLE
Problem with volumes that support node only expansion

### ISSUE THREAD

**Issue by gnufied** [kubernetes-csi/external-resizer#22]
It looks like if a CSI volume supports node only expansion and does not have controller EXPAND_VOLUME capability this resize controller will exit. 

But problem is - in that case the PV will never be updated and currently node side expansion expeects PV to have correct size before calling node side expansion. Also even if Node side expansion handled updating PV, there would be resistance to updating PV from node. 

I am thinking this controller should not exit if CSI volume does not support control-plane volume expansion but should do a noop expansion and update the PV regardless. This is how flexvolume resizing has been implemented.

cc @mlmhl @msau42 @chakri-nelluri

**Comment by gnufied** [comment]
cc @kubernetes-csi/csi-misc

**Comment by mlmhl** [comment]
> I am thinking this controller should not exit if CSI volume does not support control-plane volume expansion but should do a noop expansion and update the PV regardless.

+1

I add a `trivialResizer` in the init implement, and its original intention is to solve this problem. I think we can use a `trivialResizer` instead of `CSIResizer` to handle requests of drivers which do not have controller EXPAND_VOLUME capability. The `trivialResizer` should do nothing but mark the volume as file system resize required.

I will fix this if there is no objection.
/assign

**Comment by jsafrane** [comment]
We're in the same situation as with attacher. Initially, it was solved by `trivialAttacher` in external-attacher that marks all volumes as attached. In reality users did not understand why do they need to run attacher if their driver does not support external attach/detach.

We added a flag into CSIDriver so CSI volume plugin called by A/D controller *knows* that a volume does not support attach/detach and an just return to A/D controller that volume is attached or detacher. No external-attacher is running in this case.

IMO, we need similar flag in CSIDriver for controller-initiated expand (or how do you call it).

**Comment by mlmhl** [comment]
> IMO, we need similar flag in CSIDriver for controller-initiated expand (or how do you call it).

There is a little different between external resizer  and attacher: Even if a driver only supports node expansion, the external resizer still needs to update PVC's conditions and PV's capacity, and kubelet relies on this behavior. cc @gnufied

**Comment by gnufied** [comment]
@jsafrane @mlmhl yeah so if we did add such a flag then perhaps we can update existing in-tree controller to update PV if we know volume does not support resizing.  But lets finalize on this idea in next release when we move to beta. I think for this release having a trivial resizer seems to be fine.

**Comment by mlmhl** [comment]
> But lets finalize on this idea in next release when we move to beta. I think for this release having a trivial resizer seems to be fine.

+1

I agree that we use a trivial resizer for now, as the change of in-tree controller is not a simple work, we can solve it in next release.

**Comment by jsafrane** [comment]
> I agree that we use a trivial resizer for now, as the change of in-tree controller is not a simple work, we can solve it in next release.

Ack

**Comment by gnufied** [comment]
Fixed by #26
