### ISSUE TITLE
resize pvc with static pv ends up with panic runtime error

### ISSUE THREAD

**Issue by gaord** [kubernetes-csi/external-resizer#316]
resizing static pv ends up with invalid memory address and failed. it is csi-resizer:v1.5.0. It is expected to work with both with static and dynamic provisioned pv.

csi-resizer logs:

E0719 05:34:00.358056       1 controller.go:286] Error syncing PVC: resize volume "pv-static-doxygen" by resizer "rook-ceph.rbd.csi.ceph.com" failed: rpc error: code = Internal desc = panic runtime error: invalid memory address or nil pointer dereference
I0719 05:34:00.358211       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"doxygen-claim", UID:"632f5022-31e1-4f24-b2d7-21ed6923dd4c", APIVersion:"v1", ResourceVersion:"63861817", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pv-static-doxygen" by resizer "rook-ceph.rbd.csi.ceph.com" failed: rpc error: code = Internal desc = panic runtime error: invalid memory address or nil pointer dereference

static pv is here:

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-03-14T15:18:32Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-static-doxygen
  resourceVersion: "63856482"
  selfLink: /api/v1/persistentvolumes/pv-static-doxygen
  uid: 0f6f58a9-9fe0-441d-ac4e-022754144337
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: doxygen-claim
    namespace: default
    resourceVersion: "45658293"
    uid: 632f5022-31e1-4f24-b2d7-21ed6923dd4c
  csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: "2"
      pool: replicapool
      staticVolume: "true"
    volumeHandle: csi-vol-ce51f1d0-6b28-11ed-8b74-a2ae9ec8a708
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
status:
  phase: Bound

**Comment by gaord** [comment]
it turns out that, VolumeHandle should take form of `clusterID-poolID-volumeuniqueID`. I this case, it look like '0001-0009-rook-ceph-0000000000000002-ce51f1d0-6b28-11ed-8b74-a2ae9ec8a708'. Anyway, an informative error message will be better?

**Comment by Madhu-1** [comment]
@gaord as the issue might exist in cephcsi, which is the storage you are using, https://github.com/ceph/ceph-csi/issues might be the best place for this issue.
