### ISSUE TITLE
1.30 - [KEP-3751] VolumeAttributesClass feature add tests for beta

### ISSUE THREAD

**Issue by sunnylovestiramisu** [kubernetes-csi/external-resizer#367]
There are a few different tasks:

1. Refactor the test files for external-resizer as comment in [PR](https://github.com/kubernetes-csi/external-resizer/pull/351/files)

2. Add more unit tests to cover error cases in [this discussion](https://kubernetes.slack.com/archives/C0615MXEYDU/p1706132168286789)

3. Add end to end functional tests by consuming csi-driver-host-path

**Comment by AndrewSirenko** [comment]
Took a stab at item 1 in #402!
