### ISSUE TITLE
Upgrade external-resizer to use Debian 12 Distroless

### ISSUE THREAD

**Issue by jhawkins1** [kubernetes-csi/external-resizer#399]
Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes related projects have moved to Debian 12, we would request that external-resizer move to Debian 12 Distroless to align with other Kubernetes components.

Benefits: Alignment of the Container OS being used to other Kubernetes Components and related Projects. Reduces fan-out of multiple OSes or different versions of OSes across components. Potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS (Debian 12) release and not older LTS releases.

**Comment by kady1711** [comment]
Following up on the already submitted request regarding the migration of `external-resizer` to Debian 12 Distroless. Given the availability of Debian 12 and its adoption across the latest releases of Kubernetes and related projects, this migration is pivotal for maintaining consistency and security across Kubernetes components.

The benefits of aligning the Container OS with other Kubernetes components are clear, including reduced complexity and enhanced security, particularly with Debian's policy of fixing vulnerabilities in the latest LTS release.

Could you please provide an update on the status of this migration? Specifically, it would be very helpful to know the **targeted release date or version number** by which this change is expected to be implemented.

This information is crucial for our planning and ensures that we can maintain a secure and consistent environment across our deployments.

**Comment by sdx-jkataja** [comment]
It appears the gcr.io/distroless/static:latest base image has already changed to Debian 12.
The change has taken place some time in between the versions:

 - v1.10.1 is based on Debian 11
 - v1.11.0 is based on Debian 12
