### ISSUE TITLE
Condition `FileSystemResizePending` on pvcs with online resize enabled

### ISSUE THREAD

**Issue by maciej-tatarski** [kubernetes-csi/external-resizer#414]
While resizing the pvc with [azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) with online resize enabled. We encounter `FileSystemResizePending` condition on pvcs, which should not be there. This is just a temporary state, but still as I understand it means that manual pvc detaching is required, which should not be a case.

Related issue: https://github.com/kubernetes-csi/external-resizer/issues/36
Other related issues: https://github.com/democratic-csi/democratic-csi/issues/61#issuecomment-793127379

**Comment by gnufied** [comment]
This is just a temporary state and should go away, once node finishes expansion.
