### ISSUE TITLE
Block volumes are marked with FileSystemResizeRequired

### ISSUE THREAD

**Issue by wongma7** [kubernetes-csi/external-resizer#46]
The in-tree controller, after finishing Controller expand, checks not only if the plugin reports that FS resize is required but also if the volume is mode FS or not: https://github.com/kubernetes/kubernetes/blob/1dac5fd14a54ac4972339dbe55f9f03688fd7542/pkg/volume/util/operationexecutor/operation_generator.go#L1578 before it marks volumes FileSystemResizeRequired. 

The external-resizer should do the same.

This was caught by the e2e test
`[Driver: aws] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand [It] Verify if offline PVC expansion works`

/assign

**Comment by msau42** [comment]
I think @gnufied was also looking into this

**Comment by wongma7** [comment]
ok, looks like a 1-liner to me so let's discuss in https://github.com/kubernetes-csi/external-resizer/pull/47
