### ISSUE TITLE
Arg "--csiTimeout" is not consistent with other sidecars

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-resizer#72]
other sidecars are using `timeout` as argument example csi-provisioner https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L64

**Comment by Madhu-1** [comment]
CC @gnufied @msau42

**Comment by Madhu-1** [comment]
@jsafrane we may have to consider the your comment https://github.com/kubernetes-csi/external-provisioner/pull/402#discussion_r375213182 here also based on  the release plan

**Comment by jsafrane** [comment]
Yes, it's the same problem. If there is an user that has yaml file (helm chart, operator, ...) for a CSI driver, this yaml file should work after a minor update of any CSI sidecar (1.5 -> 1.6). We can add new options and mark the old ones as deprecated, but the old ones must still work.

**Comment by jsafrane** [comment]
Btw, thanks for keeping the cmdline options consistent!

**Comment by msau42** [comment]
This is fixed by https://github.com/kubernetes-csi/external-resizer/pull/82
/close
